project:
  type: website
  output-dir: docs


website:
  title: "Multiplexing 11/10/2022"
  twitter-card: 
    creator: "@PieRatio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/robertwwalker/pdxrug
      - icon: twitter
        href: https://twitter.com/PieRatio
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
margin-footer: |
  ![](/img/AGSMlogo.jpeg)